import { Inter } from "next/font/google";
import "./globals.css";
import Button from "./components/Button";
import Link from "next/link";
import Navbar from "./components/Navbar";
// import Page1 from "./components/Page1";

const inter = Inter({ subsets: ["latin"] });

let loggedin= false;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
        {children}
      </body>
    </html>

  
  );
}
